# DESCRIPTION: 'exp2: multi-branch'
HEAD_RATIO: 60  # %
NAME: 'exp3.CIFAR100.res32.200epoch.60'
MULTI_BRANCH: True
OUTPUT_DIR: './output/cifar100'
SHOW_STEP: 100
SAVE_STEP: 5
VALID_STEP: 1
INPUT_SIZE: (32, 32)
COLOR_SPACE: 'RGB'
CPU_MODE: False


DATASET:
  DATASET: 'IMBALANCECIFAR100'
  IMBALANCECIFAR:
    RATIO: 0.02

BACKBONE:
  TYPE: 'res32_cifar_mb'

MODULE:
  TYPE: 'GAP'

CLASSIFIER:
  TYPE: 'FC'
  BIAS: True

LOSS:
  LOSS_TYPE: 'CrossEntropy'

TRAIN:
  BATCH_SIZE: 128
  MAX_EPOCH: 200
  NUM_WORKERS: 16
  COMBINER:
    TYPE: 'default'
  OPTIMIZER:
    TYPE: 'SGD'
    BASE_LR: 0.1
    MOMENTUM: 0.9
    WEIGHT_DECAY: 2e-4
  LR_SCHEDULER:
    TYPE: 'warmup'
    LR_STEP: [120, 160]
    LR_FACTOR: 0.01
    WARM_EPOCH: 5
  TENSORBOARD:
    ENABLE: False
  SAMPLER:
    TYPE: 'default'
    DUAL_SAMPLER:
      ENABLE: True
      TYPE: 'reverse'

TRANSFORMS:
  TRAIN_TRANSFORMS: ('random_crop', 'random_horizontal_flip')
  TEST_TRANSFORMS: ()

TEST:
  BATCH_SIZE: 64
  NUM_WORKERS: 8
  MODEL_FILE: 'best_model.pth'

